title = "Zootopia (2016)"
director = "Byron Howard, Rich Moore"
summary = """
The brilliantly well-rounded Zootopia offers a thoughtful, inclusive message that's as rich and timely as its sumptuously state-of-the-art animation -- all while remaining fast and funny enough to keep younger viewers entertained.
"""
