---
- name: Update Cache
  apt:
    update_cache: yes
    upgrade: safe

- name: Create User
  import_tasks: user.yml
  tags: user

- name: Set Timezone
  timezone:
    name: America/Los_Angeles

- name: Install NodeJS
  block:
    - name: Add Key
      apt_key:
        state: present
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - name: Add Repositories
      apt_repository:
        state: present
        repo: deb http://deb.nodesource.com/node_14.x focal main
        filename: nodesource
    - name: Install NodeJS
      apt:
        state: present
        name:
          - nodejs

- name: rsync
  import_tasks: rsync.yml
  tags: rsync

- name: Update Firewall
  import_tasks: ufw.yml
  tags: ufw

- name: Prepare Application
  block:
    - name: Install
      command:
        chdir: /home/op/fox-night
        cmd: npm install

    - name: Compile
      command:
        chdir: /home/op/fox-night
        cmd: npm run build
  tags: build

- name: Systemd Start NodeJS
  import_tasks: systemd.yml
  tags: systemd

- name: Configure and Start Caddy
  import_tasks: caddy.yml
  tags: caddy
